service: lesq-api
frameworkVersion: '3'

custom:
  tableName: 'lesq-table-${sls:stage}'
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      migrate: true
      dbPath: .db
      seed: true
    seed:
      domain:
        sources:
          - table: ${self:custom.tableName}
            sources:
              - ./seeder/merchants.json
              - ./seeder/menu-live.json
              - ./seeder/menu-archived.json

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ LesQTable, Arn ]
  environment:
    LESQ_TABLE: ${self:custom.tableName}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

  menu-api:
    handler: handler/menu.handler
    events:
      - http:
          path: 'api/merchants/{merchantId}/menu/{default*}'
          method: '*'
  product-api:
    handler: handler/product.handler
    events:
      - http:
          path: '/api/merchants/{merchantId}/products/{default*}'
          method: '*'

  # product-create:
  #   handler: handler/product.create
  #   events:
  #     - http:
  #         path: api/merchants/{merchantId}/products
  #         method: post
  # product-get:
  #   handler: handler/product.get
  #   events:
  #     - http:
  #         path: api/merchants/{merchantId}/products/{productId}
  #         method: get

resources:
  Resources:
    LesQTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: MenuPK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: MenuIndex
            KeySchema:
            - AttributeName: MenuPK
              KeyType: HASH
            - AttributeName: SK
              KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}

plugins:
  - serverless-dynamodb-local
  - serverless-offline
